# auth-web-community/pnpm-workspace.yaml
# 单包项目也可只用此文件承载 pnpm 配置（pnpm 10+）

shamefullyHoist: true
shellEmulator: true
enablePrePostScripts: false
strictPeerDependencies: false

# 原 package.json → pnpm.allowedDeprecatedVersions
allowedDeprecatedVersions:
  are-we-there-yet: "*"
  sourcemap-codec: "*"
  lodash.isequal: "*"
  domexception: "*"
  w3c-hr-time: "*"
  inflight: "*"
  npmlog: "*"
  rimraf: "*"
  stable: "*"
  gauge: "*"
  abab: "*"
  glob: "*"

# 原 package.json → pnpm.onlyBuiltDependencies
onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js
  - es5-ext
  - esbuild
  - typeit
  - vue-demi

# 原 package.json → pnpm.ignoredBuiltDependencies
ignoredBuiltDependencies:
  - "@tailwindcss/oxide"

allowBuilds:
  '@parcel/watcher': true
  es5-ext: set this to true or false
  esbuild: true
  vue-demi: true
