/**
 * 鉴权相关稳定错误码（与网关/认证服务约定一致，供恢复策略与错误判定共用）。
 */
export const AUTH_ERROR_CODES = {
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_MISSING: 'TOKEN_MISSING',
  SESSION_MISSING: 'SESSION_MISSING',
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_KIND_MISMATCH: 'TOKEN_KIND_MISMATCH',
  SESSION_DISABLED: 'SESSION_DISABLED',
  PERMISSION_VERSION_MISMATCH: 'PERMISSION_VERSION_MISMATCH',
  GATEWAY_UNAUTHORIZED: 'GATEWAY_UNAUTHORIZED',
} as const;

/**
 * 权限版本冲突错误码列表
 */
export const PERMISSION_VERSION_MISMATCH_CODES: readonly string[] = [AUTH_ERROR_CODES.PERMISSION_VERSION_MISMATCH];
