/**
 * 会改变鉴权恢复 / 冲突分支的稳定错误码（与网关/认证服务约定一致）。
 */
export const AUTH_ERROR_CODES = {
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_MISSING: 'TOKEN_MISSING',
  SESSION_MISSING: 'SESSION_MISSING',
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  PERMISSION_VERSION_MISMATCH: 'PERMISSION_VERSION_MISMATCH',
} as const;
